      <li><a href='${varpath}'>Home</a></li>
      <li><a href='${varpath}sys/introduction/'>Introduction »</a>
        <ul>
          <li><a href='${varpath}sys/introduction/vision'>Vision</a></li>
          <li><a href='${varpath}sys/introduction/values'>Values</a></li>
          <ul>
            <li><a href='${varpath}sys/introduction/values/differences'>Differences</a></li>
          </ul>
          <li><a href='${varpath}sys/introduction/site'>Site</a></li>
          <li><a href='${varpath}sys/introduction/money'>Money</a></li>
          <li><a href='${varpath}sys/introduction/behaviour'>Behaviour</a></li>
          <li><a href='${varpath}sys/introduction/limits'>Limits</a></li>
        </ul>
      </li>
      <li><a href='${varpath}sys/community'>Community »</a>
        <ul>
          <li><a href='${varpath}sys/community/resources'>Resources</a></li>
          <li><a href='${varpath}sys/community/blogs'>Blogs</a></li>
        </ul>
      </li>
      <li><a href='${varpath}sys/challenges'>Challenges »</a>
        <ul>
          <li><a href='${varpath}sys/challenges/framework'>Framework</a></li>
          <li><a href='${varpath}sys/challenges/responses'>Responses</a></li>
        </ul>
      </li>
      <li><a href='${varpath}sys/contact'>Contact »</a>
