      <li><a href='${varpath}'>Home</a></li>
      <li><a href='${varpath}sys/introduction/'>Introduction »</a>
        <ul>
          <li><a href='${varpath}sys/introduction/vision'>Vision</a></li>
          <li><a href='${varpath}sys/introduction/values'>Values</a></li>
          <li><a href='${varpath}sys/introduction/site'>Site</a></li>
          <li><a href='${varpath}sys/introduction/money'>Money</a></li>
          <li><a href='${varpath}sys/introduction/behaviour'>Behaviour</a></li>
          <li><a href='${varpath}sys/introduction/limits'>Limits</a></li>
        </ul>
      </li>
      <li><a href='${varpath}sys/community'>Community »</a>
        <ul>
          <li><a href='${varpath}sys/community/resources'>Resources</a></li>
        </ul>
      </li>
      <li><a href='${varpath}sys/challenges'>Challenges »</a>
        <ul>
          <li><a href='${varpath}sys/challenges/framework'>Framework</a></li>
          <li><a href='${varpath}sys/challenges/responses'>Responses</a></li>
        </ul>
      </li>
      <li><a href='${varpath}m'>Partners »</a>
        <ul>
          <li><a href='${varpath}m/sm'>Sea Mills</a></li>
        </ul>
      </li>
      <li><a href='${varpath}support'>Support</a></li>
      <li><a href='${varpath}contact'>Contact</a></li>
